include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    use_if_null_to_convert_nulls_to_bools: false
    prefer_int_literals: false
