name: budget_intelli
description: "App to manage your budget and expenses."
publish_to: "none"

version: 1.1.1+68

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  android_intent_plus: ^5.1.0
  app_settings: ^5.1.1
  auto_size_text: ^3.0.0
  back_button_interceptor: ^8.0.0
  calendar_date_picker2: ^1.0.2
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.0.1
  cupertino_icons: ^1.0.6
  currency_text_input_formatter: ^2.2.1
  device_info_plus: ^11.1.1
  dropdown_button2: ^2.3.9
  dropdown_search: ^6.0.1
  easy_date_timeline: ^1.1.3
  equatable: ^2.0.5
  expressions: ^0.2.5+1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.3
  firebase_storage: ^12.0.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_color_picker_plus: ^2.0.1
  flutter_dotenv: ^5.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^3.0.1
  fluttertoast: ^8.2.4
  fpdart: ^1.1.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get_it: ^8.0.2
  go_router: ^14.0.0
  google_generative_ai: ^0.4.3
  google_mobile_ads: ^5.1.0
  image: ^4.2.0
  image_picker: ^1.0.7
  in_app_purchase: ^3.2.0
  internet_connection_checker_plus: ^2.3.0
  intl: any
  json_annotation: ^4.8.1
  local_auth: ^2.2.0
  local_auth_android: ^1.0.42
  logger: ^2.2.0
  lottie: ^3.1.0
  math_expressions: ^2.4.0
  mockito: ^5.4.4
  open_file: ^3.3.2
  path: ^1.9.0
  path_provider: ^2.1.4
  pdf: ^3.11.0
  percent_indicator: ^4.2.3
  rive: ^0.13.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  timezone: ^0.10.0
  url_launcher: ^6.3.0
  uuid: ^4.3.3
  very_good_analysis: ^6.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockingjay: ^0.5.0
  mocktail: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/png/
    - assets/icons/expense/
    - assets/icons/family/
    - assets/icons/svg/
    - assets/icons/riv/
    - assets/json/
    - .env

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist-ExtraLightItalic.ttf
        - asset: assets/fonts/Urbanist-Italic.ttf
        - asset: assets/fonts/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist-LightItalic.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist-ThinItalic.ttf

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/splash-logo.png"
#   adaptive_icon_foreground: "assets/images/splash-logo.png"
#   adaptive_icon_background: "#39693b"
#   min_sdk_android: 21
#   remove_alpha_ios: true

#   launcher_name:
#     default: "Animated Splash Screen."

flutter_native_splash:
  color: "#39693b"
  image: assets/images/budget_intelli_splash.png
  color_dark: "#39693b"
  android_12:
    image: assets/images/budget_intelli_splash.png
  android: true
  ios: true
