import 'package:budget_intelli/core/core.dart';

List<Map<String, dynamic>> iconPathList = [
  {'name': 'Book', 'path': bookPng},
  {'name': 'Budget', 'path': budget},
  {'name': 'Calculate', 'path': calculate},
  {'name': 'Cloth', 'path': cloth},
  {'name': 'Coffee', 'path': coffee},
  {'name': 'Drink', 'path': drink},
  {'name': 'Electricity', 'path': electricity},
  {'name': 'Entertainment', 'path': entertainmentPng},
  {'name': 'Fast Food', 'path': fastFood},
  {'name': 'Financial', 'path': financial},
  {'name': 'Food', 'path': foodPng},
  {'name': 'Fruit', 'path': fruit},
  {'name': 'Gas', 'path': gas},
  {'name': 'Gift', 'path': giftPng},
  {'name': 'Groceries', 'path': groceries},
  {'name': 'Gym', 'path': gym},
  {'name': 'Income', 'path': income},
  {'name': 'Insurance', 'path': insurancePng},
  {'name': 'Investment', 'path': investmentPng},
  {'name': 'Laundry', 'path': laundry},
  {'name': 'Magazine', 'path': magazine},
  {'name': 'Massage', 'path': massage},
  {'name': 'Medical', 'path': medical},
  {'name': 'Mortgage', 'path': mortgage},
  {'name': 'Movie', 'path': movie},
  {'name': 'Music', 'path': music},
  {'name': 'Painting', 'path': painting},
  {'name': 'Parking', 'path': parking},
  {'name': 'Public Transport', 'path': publicTransport},
  {'name': 'Salon', 'path': salon},
  {'name': 'Shopping Cart', 'path': shoppingCart},
  {'name': 'Snack', 'path': snack},
  {'name': 'Toy', 'path': toy},
  {'name': 'Travel', 'path': travelPng},
  {'name': 'Wallet', 'path': wallet},
  {'name': 'Bed Time', 'path': bedTimePng},
  {'name': 'Baby', 'path': babyPng},
  {'name': 'Pregnancy', 'path': pregnancyPng},
  {'name': 'Laundry', 'path': laundryPng},
  {'name': 'Baseball Ball', 'path': baseballBallPng},
  {'name': 'Baby Pacifier', 'path': babyPacifierPng},
  {'name': 'Motherhood', 'path': motherhoodPng},
  {'name': 'Swimming Pool', 'path': swimmingPoolPng},
  {'name': 'Fireplace', 'path': fireplacePng},
  {'name': 'Family Tree', 'path': familyTreePng},
  {'name': 'Family', 'path': familyPng},
  {'name': 'Riding', 'path': ridingPng},
  {'name': 'Washing Dishes', 'path': washingDishesPng},
  {'name': 'Pig', 'path': pigPng},
  {'name': 'Family 2', 'path': family2Png},
  {'name': 'Pet', 'path': petPng},
  {'name': 'Decoration', 'path': decorationPng},
  {'name': 'Flying', 'path': flyingPng},
  {'name': 'Tools', 'path': toolsPng},
  {'name': 'Tasks', 'path': tasksPng},
  {'name': 'Moving Truck', 'path': movingTruckPng},
  {'name': 'Ironing', 'path': ironingPng},
  {'name': 'Bunk Bed', 'path': bunkBedPng},
  {'name': 'Father and Son', 'path': fatherAndSonPng},
  {'name': 'Breeding', 'path': breedingPng},
  {'name': 'Cooking', 'path': cookingPng},
  {'name': 'Home', 'path': homePng},
  {'name': 'Photography', 'path': photographyPng},
  {'name': 'Family 2', 'path': familyPng2},
  {'name': 'Brothers', 'path': brothersPng},
  {'name': 'Grandmother', 'path': grandmotherPng},
  {'name': 'Newborn', 'path': newbornPng},
  {'name': 'Marriage', 'path': marriagePng},
  {'name': 'Pregnancy Test', 'path': pregnancyTestPng},
  {'name': 'Family Picture', 'path': familyPicturePng},
  {'name': 'Pet Care', 'path': petCarePng},
  {'name': 'Shopping Bag', 'path': shoppingBagPng},
  {'name': 'Home 2', 'path': homePng2},
  {'name': 'Mom', 'path': momPng},
  {'name': 'Baby Girl', 'path': babyGirlPng},
  {'name': 'Budget', 'path': budgetPng},
  {'name': 'Grandfather', 'path': grandfatherPng},
  {'name': 'Pets', 'path': petsPng},
  {'name': 'Mother and Son', 'path': motherAndSonPng},
  {'name': 'Birthday', 'path': birthdayPng},
  {'name': 'Swing', 'path': swingPng},
  {'name': 'Vacations', 'path': vacationsPng},
  {'name': 'Family 3', 'path': familyPng3},
  {'name': 'Subscriptions', 'path': subscriptionsPng},
  {'name': 'Debt', 'path': debtPng},
  {'name': 'Paylater', 'path': payLaterPng},
  {'name': 'Saving', 'path': savingPng},
  {'name': 'Emergency Fund', 'path': emergencyFundPng},
  {'name': 'Rent', 'path': rentPng},
  {'name': 'Credit Card', 'path': creditCardPng},
  {'name': 'Dining Out', 'path': diningOutPng},
  {'name': 'Donation', 'path': donationPng},
  {'name': 'Education', 'path': educationPng},
  {'name': 'Health Care', 'path': healthCarePng},
  {'name': 'Home Repairment', 'path': homeRepairmentPng},
  {'name': 'Sports', 'path': sportsPng},
  {'name': 'Utility', 'path': utilityPng},
  {'name': 'Youtube', 'path': youtubePng},
  {'name': 'Spotify', 'path': spotifyPng},
  {'name': 'Netflix', 'path': netflixPng},
];
